const state = { menu: [], cart: JSON.parse(localStorage.getItem('plateful-cart') || '[]'), filter: 'All', user: JSON.parse(localStorage.getItem('plateful-user') || 'null'), token: localStorage.getItem('plateful-token'), lastOrder: localStorage.getItem('plateful-last-order'), registering: false, map: null };
const money = value => `₹${value.toLocaleString('en-IN')}`;
const save = () => localStorage.setItem('plateful-cart', JSON.stringify(state.cart));
const itemInCart = id => state.cart.find(item => item.menuItemId === id);
const authHeaders = () => state.token ? { Authorization: `Bearer ${state.token}` } : {};
async function loadMenu() { state.menu = await fetch('/api/menu').then(res => res.json()); renderFilters(); renderMenu(); renderCart(); renderAccount(); }
function renderAccount() { document.querySelector('#open-auth').textContent = state.user ? `Hi, ${state.user.name.split(' ')[0]} · Sign out` : 'Sign in'; }
function renderFilters() { const categories = ['All', ...new Set(state.menu.map(item => item.category))]; document.querySelector('#filters').innerHTML = categories.map(category => `<button class="filter ${state.filter === category ? 'active' : ''}" data-filter="${category}">${category}</button>`).join(''); }
function renderMenu() { const dishes = state.filter === 'All' ? state.menu : state.menu.filter(item => item.category === state.filter); document.querySelector('#menu-grid').innerHTML = dishes.map(item => `<article class="dish"><div class="dish-image" style="background:${item.color}"><img src="${item.image}" alt="${item.name}" loading="lazy" onerror="this.hidden=true"><span>${item.emoji}</span><em>${item.category}</em></div><div class="dish-info"><div><h3>${item.name}</h3><p>${item.description}</p></div><div class="dish-bottom"><strong>${money(item.price)}</strong><button class="add" data-add="${item.id}" aria-label="Add ${item.name}">+</button></div></div></article>`).join(''); }
function changeQuantity(id, amount) { const found = itemInCart(id); if (!found && amount > 0) state.cart.push({ menuItemId: id, quantity: 1 }); else if (found) { found.quantity += amount; if (found.quantity <= 0) state.cart = state.cart.filter(item => item !== found); } save(); renderCart(); }
function renderCart() { const rows = state.cart.map(cartItem => ({ ...state.menu.find(item => item.id === cartItem.menuItemId), quantity: cartItem.quantity })).filter(item => item.id); const total = rows.reduce((sum, item) => sum + item.price * item.quantity, 0); document.querySelector('#cart-count').textContent = rows.reduce((sum, item) => sum + item.quantity, 0); document.querySelector('#cart-total').textContent = money(total); document.querySelector('#cart-items').innerHTML = rows.length ? rows.map(item => `<div class="cart-row"><span class="mini-emoji">${item.emoji}</span><div><h3>${item.name}</h3><p>${money(item.price)}</p></div><div class="quantity"><button data-change="${item.id}" data-amount="-1">−</button><b>${item.quantity}</b><button data-change="${item.id}" data-amount="1">+</button></div></div>`).join('') : '<div class="empty"><span>🍽️</span><h3>Your bag is empty</h3><p>Add something delicious from the menu.</p></div>'; document.querySelector('#checkout').disabled = !rows.length; }
function toggleCart(open) { document.querySelector('#cart-panel').classList.toggle('open', open); document.querySelector('#overlay').classList.toggle('show', open); }
function openAuth() { if (state.user) { state.user = null; state.token = null; localStorage.removeItem('plateful-user'); localStorage.removeItem('plateful-token'); return renderAccount(); } document.querySelector('#auth-dialog').showModal(); }
function toggleAuthMode() { state.registering = !state.registering; document.querySelector('#auth-eyebrow').textContent = state.registering ? 'WELCOME TO PLATEFUL' : 'WELCOME BACK'; document.querySelector('#auth-title').textContent = state.registering ? 'Create your account' : 'Sign in to Plateful'; document.querySelector('#name-field').hidden = !state.registering; document.querySelector('#name-field input').required = state.registering; document.querySelector('#auth-submit').innerHTML = state.registering ? 'Create account <span>→</span>' : 'Sign in <span>→</span>'; document.querySelector('#auth-question').textContent = state.registering ? 'Already have an account?' : 'New to Plateful?'; document.querySelector('#toggle-auth').textContent = state.registering ? 'Sign in' : 'Create an account'; document.querySelector('#auth-error').textContent = ''; }
async function showTracking() { if (!state.lastOrder) return; const dialog = document.querySelector('#tracking-dialog'); dialog.showModal(); const tracking = await fetch(`/api/orders/${state.lastOrder}/tracking`).then(res => res.json()); document.querySelector('#tracking-title').textContent = tracking.status; document.querySelector('#tracking-eta').textContent = `Your rider is ${tracking.etaMinutes} minutes away. We’ll keep updating this as they travel.`; if (!window.L) return; if (state.map) state.map.remove(); state.map = L.map('tracking-map', { zoomControl: false }).setView([12.953, 77.61], 12); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '© OpenStreetMap' }).addTo(state.map); const marker = (point, symbol, color) => L.marker([point.lat, point.lng], { icon: L.divIcon({ className: 'map-pin', html: `<b style="background:${color}">${symbol}</b>`, iconSize: [32, 32] }) }).addTo(state.map); marker(tracking.restaurant, '🍴', '#eb5e28'); marker(tracking.driver, '🛵', '#17231d'); marker(tracking.destination, '⌂', '#397a5c'); L.polyline([[tracking.restaurant.lat, tracking.restaurant.lng], [tracking.destination.lat, tracking.destination.lng]], { color: '#eb5e28', weight: 4, dashArray: '7 8' }).addTo(state.map); setTimeout(() => state.map.invalidateSize(), 150); }
document.addEventListener('click', event => { const filter = event.target.closest('[data-filter]'); const add = event.target.closest('[data-add]'); const change = event.target.closest('[data-change]'); if (filter) { state.filter = filter.dataset.filter; renderFilters(); renderMenu(); } if (add) { changeQuantity(add.dataset.add, 1); toggleCart(true); } if (change) changeQuantity(change.dataset.change, Number(change.dataset.amount)); });
document.querySelector('#open-cart').onclick = () => toggleCart(true); document.querySelector('#close-cart').onclick = () => toggleCart(false); document.querySelector('#overlay').onclick = () => toggleCart(false); document.querySelector('#open-auth').onclick = openAuth; document.querySelector('#toggle-auth').onclick = toggleAuthMode;
document.querySelector('#checkout').onclick = () => document.querySelector('#checkout-dialog').showModal(); document.querySelector('#track-order').onclick = () => { document.querySelector('#success-dialog').close(); showTracking(); };
document.querySelectorAll('.modal-close').forEach(button => button.onclick = () => button.closest('dialog').close());
document.querySelector('#auth-form').onsubmit = async event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); const result = await fetch(state.registering ? '/api/auth/register' : '/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const body = await result.json(); if (!result.ok) return document.querySelector('#auth-error').textContent = body.error; state.user = body.user; state.token = body.token; localStorage.setItem('plateful-user', JSON.stringify(body.user)); localStorage.setItem('plateful-token', body.token); document.querySelector('#auth-dialog').close(); event.target.reset(); renderAccount(); };
document.querySelector('#checkout-form').onsubmit = async event => { event.preventDefault(); const form = new FormData(event.target); const button = event.submitter; button.disabled = true; button.textContent = 'Placing order…'; const result = await fetch('/api/orders', { method: 'POST', headers: { 'Content-Type': 'application/json', ...authHeaders() }, body: JSON.stringify({ customer: Object.fromEntries(form), items: state.cart }) }); const body = await result.json(); button.disabled = false; button.innerHTML = 'Place order <span>→</span>'; if (!result.ok) return document.querySelector('#form-error').textContent = body.error; state.lastOrder = body.id; localStorage.setItem('plateful-last-order', body.id); state.cart = []; save(); renderCart(); toggleCart(false); document.querySelector('#checkout-dialog').close(); document.querySelector('#success-text').textContent = `Order #${body.id} is confirmed. We’ll deliver it to ${body.customer.address}.`; document.querySelector('#success-dialog').showModal(); event.target.reset(); };
loadMenu().catch(() => document.querySelector('#menu-grid').innerHTML = '<p>Unable to load the menu. Please refresh.</p>');
